import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Navbar } from '@/components/Navbar';
import { WeeklyDeal, ShopByPet, ShopByBrand, Subscribe } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>FurryMart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={`${inter.className} py-0  lg:py-7`}>
        <div className="px-3 lg:px-32">
          <WeeklyDeal />
        </div>

        <Subscribe />

        <div className="px-3 lg:px-32">
          <ShopByPet />
          <ShopByBrand />
        </div>
      </main>
    </>
  );
}
