import Head from 'next/head';
import { Inter } from 'next/font/google';
import { Navbar } from '@/components/Navbar';
import { WeeklyDeal, ShopByPet } from '@/components';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>FurryMart</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <main className={`${inter.className} px-5 py-0 lg:px-10 lg:py-7`}>
        <WeeklyDeal />
        <ShopByPet />
      </main>
    </>
  );
}
